-- =====================================================================
-- Tabelle dei ticket MHXR (segnalazioni dal sito) e della loro conversazione
-- =====================================================================
--
-- DOVE LANCIARLO:
--   Supabase -> il tuo progetto -> SQL Editor -> New query -> incolla -> Run
--
-- PERCHE' A MANO E NON CON UNA MIGRATION EF:
--   Le migration nel repo non corrispondono al database reale (page_visits
--   e' stata creata a mano con nomi di colonna diversi da quelli che
--   genererebbe EF). Un "dotnet ef database update" rischierebbe di creare
--   tabelle doppie o fallire a meta'.
--
-- E' SICURO RILANCIARLO ANCHE PIU' VOLTE: ogni pezzo qui sotto controlla da
-- solo se serve ancora fare qualcosa, quindi non duplica e non rompe nulla
-- se lo lanci di nuovo su un database gia' aggiornato.
-- =====================================================================

CREATE TABLE IF NOT EXISTS "MhxrTickets" (
    -- Numero del ticket, generato dal database
    "Id"          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Tipo di segnalazione scelto dalla tendina.
    -- I valori ammessi li controlla anche il server (MhxrTicketCategorie),
    -- qui c'e' un vincolo di lunghezza per non farci scrivere un romanzo.
    "Categoria"   varchar(60) NOT NULL,

    -- true  = ticket aperto da un visitatore senza account
    -- false = ticket aperto da un utente che ha fatto login
    -- E' il campo che ti serve per distinguerli a colpo d'occhio.
    "Anonimo"     boolean NOT NULL DEFAULT true,

    -- Chi l'ha aperto: email (o id Auth0) se loggato, NULL se anonimo.
    -- Lo riempie il SERVER leggendo il token, non il browser: cosi' nessuno
    -- puo' spacciarsi per un altro.
    "Autore"      text,

    -- Aperto (aspetta te) / Preso in carico / Risposto (aspetta lui) / Chiuso.
    -- Solo TU puoi chiudere un ticket: l'utente non ha quel potere, puo'
    -- solo scrivere e aspettare.
    "Stato"       varchar(20) NOT NULL DEFAULT 'Aperto',

    -- Quando e' stato aperto
    "CreatedAt"   timestamp with time zone NOT NULL DEFAULT now(),

    -- Solo per i ticket anonimi: il "biglietto" salvato nel browser di chi
    -- scrive, per farsi riconoscere senza account. NULL per chi e' loggato.
    "LookupToken" text,

    -- Solo per i ticket anonimi: serve per il limite "un ticket alla volta"
    -- quando non c'e' un account con cui riconoscere chi scrive.
    "IndirizzoIp" text
);

-- L'elenco si guarda quasi sempre dal piu' recente, e spesso filtrato per
-- stato ("fammi vedere solo quelli aperti"): questo indice serve a quello.
CREATE INDEX IF NOT EXISTS "IX_MhxrTickets_Stato_CreatedAt"
    ON "MhxrTickets" ("Stato", "CreatedAt" DESC);

-- Se la tabella esisteva gia' da un tentativo precedente senza queste
-- colonne, questo la mette in pari senza toccare le righe gia' presenti.
ALTER TABLE "MhxrTickets" ADD COLUMN IF NOT EXISTS "LookupToken" text;
ALTER TABLE "MhxrTickets" ADD COLUMN IF NOT EXISTS "IndirizzoIp" text;


-- =====================================================================
-- Conversazione: ogni messaggio (apertura, risposte, richieste di
-- chiarimento) e' una riga qui, invece di due colonne fisse "Messaggio"/
-- "Risposta" sul ticket. Serve per far scambiare piu' messaggi avanti e
-- indietro tra utente e admin, non solo un messaggio + una risposta.
-- =====================================================================
CREATE TABLE IF NOT EXISTS "MhxrTicketMessaggi" (
    "Id"        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- A quale ticket appartiene. ON DELETE CASCADE: se un giorno elimini un
    -- ticket a mano, non restano messaggi orfani da pulire a parte.
    "IdTicket"  integer NOT NULL REFERENCES "MhxrTickets" ("Id") ON DELETE CASCADE,

    -- Chi l'ha scritto: 'Utente' o 'Admin' (vedi MhxrMittente nel codice).
    "Mittente"  varchar(10) NOT NULL,

    "Testo"     text NOT NULL,

    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now()
);

-- La conversazione si legge sempre "tutti i messaggi di QUESTO ticket, in
-- ordine di data": questo indice serve esattamente a quello.
CREATE INDEX IF NOT EXISTS "IX_MhxrTicketMessaggi_IdTicket_CreatedAt"
    ON "MhxrTicketMessaggi" ("IdTicket", "CreatedAt");


-- =====================================================================
-- MIGRAZIONE: sposta il contenuto delle vecchie colonne "Messaggio"/
-- "Risposta"/"RispostoAt" (se esistono ancora, da prima che ci fosse questa
-- tabella) dentro la conversazione, cosi' non perdi i ticket di prova che
-- hai gia' aperto. Ha un controllo "non esiste ancora" per ogni riga, quindi
-- e' sicuro rilanciarlo piu' volte: non duplica i messaggi.
-- =====================================================================
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'MhxrTickets' AND column_name = 'Messaggio'
    ) THEN
        INSERT INTO "MhxrTicketMessaggi" ("IdTicket", "Mittente", "Testo", "CreatedAt")
        SELECT t."Id", 'Utente', t."Messaggio", t."CreatedAt"
        FROM "MhxrTickets" t
        WHERE t."Messaggio" IS NOT NULL
          AND NOT EXISTS (
              SELECT 1 FROM "MhxrTicketMessaggi" m
              WHERE m."IdTicket" = t."Id" AND m."Mittente" = 'Utente'
          );
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'MhxrTickets' AND column_name = 'Risposta'
    ) THEN
        INSERT INTO "MhxrTicketMessaggi" ("IdTicket", "Mittente", "Testo", "CreatedAt")
        SELECT t."Id", 'Admin', t."Risposta", COALESCE(t."RispostoAt", t."CreatedAt")
        FROM "MhxrTickets" t
        WHERE t."Risposta" IS NOT NULL
          AND NOT EXISTS (
              SELECT 1 FROM "MhxrTicketMessaggi" m
              WHERE m."IdTicket" = t."Id" AND m."Mittente" = 'Admin'
          );
    END IF;
END $$;

-- Le vecchie colonne non servono piu': tutto e' stato copiato sopra.
ALTER TABLE "MhxrTickets" DROP COLUMN IF EXISTS "Messaggio";
ALTER TABLE "MhxrTickets" DROP COLUMN IF EXISTS "Risposta";
ALTER TABLE "MhxrTickets" DROP COLUMN IF EXISTS "RispostoAt";


-- =====================================================================
-- VERIFICA: lancia anche queste due, "MhxrTickets" deve avere 7 colonne
-- (Id, Categoria, Anonimo, Autore, Stato, CreatedAt, LookupToken,
-- IndirizzoIp - occhio, sono 8 in realta', il commento sopra e' indicativo)
-- e "MhxrTicketMessaggi" le sue 5, coi ticket di prova gia' migrati dentro.
-- =====================================================================
SELECT column_name, data_type, is_nullable, column_default
FROM information_schema.columns
WHERE table_name = 'MhxrTickets'
ORDER BY ordinal_position;

SELECT column_name, data_type, is_nullable, column_default
FROM information_schema.columns
WHERE table_name = 'MhxrTicketMessaggi'
ORDER BY ordinal_position;

SELECT * FROM "MhxrTicketMessaggi" ORDER BY "IdTicket", "CreatedAt";
