-- =====================================================================
-- Tabella dei ticket MHXR (segnalazioni dal sito)
-- =====================================================================
--
-- DOVE LANCIARLO:
--   Supabase -> il tuo progetto -> SQL Editor -> New query -> incolla -> Run
--
-- PERCHE' A MANO E NON CON UNA MIGRATION EF:
--   Le migration nel repo non corrispondono al database reale (page_visits
--   e' stata creata a mano con nomi di colonna diversi da quelli che
--   genererebbe EF). Un "dotnet ef database update" rischierebbe di creare
--   tabelle doppie o fallire a meta'.
--
-- E' SICURO RILANCIARLO: "IF NOT EXISTS" lo rende innocuo se gia' eseguito.
-- =====================================================================

CREATE TABLE IF NOT EXISTS "MhxrTickets" (
    -- Numero del ticket, generato dal database
    "Id"          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Tipo di segnalazione scelto dalla tendina.
    -- I valori ammessi li controlla anche il server (MhxrTicketCategorie),
    -- qui c'e' un vincolo di lunghezza per non farci scrivere un romanzo.
    "Categoria"   varchar(60) NOT NULL,

    -- Il messaggio scritto dall'utente
    "Messaggio"   text NOT NULL,

    -- true  = ticket aperto da un visitatore senza account
    -- false = ticket aperto da un utente che ha fatto login
    -- E' il campo che ti serve per distinguerli a colpo d'occhio.
    "Anonimo"     boolean NOT NULL DEFAULT true,

    -- Chi l'ha aperto: email (o id Auth0) se loggato, NULL se anonimo.
    -- Lo riempie il SERVER leggendo il token, non il browser: cosi' nessuno
    -- puo' spacciarsi per un altro.
    "Autore"      text,

    -- Serve a te per gestirli: Aperto / Preso in carico / Risposto / Chiuso
    "Stato"       varchar(20) NOT NULL DEFAULT 'Aperto',

    -- Quando e' arrivato
    "CreatedAt"   timestamp with time zone NOT NULL DEFAULT now(),

    -- La tua risposta all'utente, NULL finche' non rispondi.
    "Risposta"    text,

    -- Quando hai risposto (serve al Client per mostrare la conversazione)
    "RispostoAt"  timestamp with time zone,

    -- Solo per i ticket anonimi: il "biglietto" salvato nel browser di chi
    -- scrive, per farsi riconoscere senza account. NULL per chi e' loggato.
    "LookupToken" text,

    -- Solo per i ticket anonimi: serve per il limite "un ticket alla volta"
    -- quando non c'e' un account con cui riconoscere chi scrive.
    "IndirizzoIp" text
);


-- L'elenco si guarda quasi sempre dal piu' recente, e spesso filtrato per
-- stato ("fammi vedere solo quelli aperti"): questo indice serve a quello.
CREATE INDEX IF NOT EXISTS "IX_MhxrTickets_Stato_CreatedAt"
    ON "MhxrTickets" ("Stato", "CreatedAt" DESC);

-- Se la tabella esisteva gia' da un tentativo precedente senza queste
-- colonne, questo la mette in pari senza toccare le righe gia' presenti.
-- Sicuro rilanciarlo anche se la tabella e' gia' completa: "IF NOT EXISTS"
-- non fa nulla quando la colonna c'e' gia'.
ALTER TABLE "MhxrTickets" ADD COLUMN IF NOT EXISTS "Risposta" text;
ALTER TABLE "MhxrTickets" ADD COLUMN IF NOT EXISTS "RispostoAt" timestamp with time zone;
ALTER TABLE "MhxrTickets" ADD COLUMN IF NOT EXISTS "LookupToken" text;
ALTER TABLE "MhxrTickets" ADD COLUMN IF NOT EXISTS "IndirizzoIp" text;


-- =====================================================================
-- VERIFICA: lancia anche questa, devi vedere le 11 colonne qui sopra
-- =====================================================================
SELECT column_name, data_type, is_nullable, column_default
FROM information_schema.columns
WHERE table_name = 'MhxrTickets'
ORDER BY ordinal_position;
